Update Vagrantfile template
* Use up-to-date default images
* Remove SSH user name for Google likely causing the weired rsync error due to wrong authentication:

    ```
    There was an error when attemping to rsync a share folder.
    Please inspect the error message below for more info.

    Host path: /var/www/cloud-workbench/shared/storage/production/benchmark_executions/002-_migration__google_test/0012/vagrant/
    Guest path: /vagrant
    Error: protocol version mismatch -- is your shell clean?
    (see the rsync man page for an explanation)
    rsync error: protocol incompatibility (code 2) at compat.c(176) [sender=3.1.1]
    ```